server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api?userSSL=false
    username: root
    password: ZylLx930101
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 60000
      connection-timeout: 5000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zyl.domain
