server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/api?userSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: ZylLx930101
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 60000
      connection-timeout: 5000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
logging:
  config: classpath:log4j2-prod.xml
